; Each new term in the Fibonacci sequence is
; generated by adding the previous two terms.
; By starting with 1 and 2, the first 10 terms will be:

; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

; By considering the terms in the Fibonacci sequence
; whose values do not exceed four million, find the
; sum of the even-valued terms.

(defn fib [n]
  (if (or (= n 1) (= n 2))
    1
    (+ (fib (- n 1)) (fib (- n 2)))
  )
)

(defn even-fib [n sum]
  (def res (fib n))
  (cond
    (= (mod res 2) 0)
      (even-fib (+ n 1) (+ sum res))
    (> res 4000000)
      sum
    :default (even-fib (+ n 1) sum)
  )
)

(println (even-fib 1 0))
